# Default Profiles Setting

# Spring Boot Config
spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always

# Server Config
server:
  port: 8090
  servlet: 
    context-path: /

# Swagger Config
springdoc:
  version: v0.0.1
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
#    enabled: false
    enabled: true
#    groups:
#      enabled: true
  swagger-ui:
    path: restapi-doc
    enabled: true
#    enabled: false
#    url: /v3/api-docs/restapi.json
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
  writer-with-order-by-keys: true
  paths-to-match:
    - /api/**

# Logback Config
logging:
  file:
    name: restapi
    schedule_name: restScheduling
  level:
    root: off
    default_level: info
    pretty: off
    org.zalando.logbook: off
    schedule_level: off
    com.custom: debug
    jdbc:
      default: ERROR
      sqlonly: OFF
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 1GB

# MariaDB Config
Globals:
  DbType: maria
  maria:
#    DriverClassName: org.mariadb.jdbc.Driver
    DriverClassName: net.sf.log4jdbc.DriverSpy
#    Url: jdbc:mariadb://localhost:3306/custom
    Url: jdbc:log4jdbc:mariadb://localhost:3306/custom?allowPublicKeyRetrieval=true&useSSL=false
    UserName: root
    Password: 220617
  page:
    pageUnit: 10
    pageSize: 10
    paging: false
