# 클라우드 운영 서버(Prod) development environment Profiles Setting
spring:
  config:
    activate:
      on-profile: local

# Logging Config
logging:
  file:
    path: c:/tmp//local
  level:
    root: info
    default_level: debug
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 1GB

# MariaDB Config
Globals:
  DbType: maria
  maria:
#    DriverClassName: org.mariadb.jdbc.Driver
    DriverClassName: net.sf.log4jdbc.DriverSpy
#    Url: jdbc:mariadb://211.240.5.143:3306/hisco
    Url: jdbc:log4jdbc:mariadb://211.240.5.143:3306/hisco
    UserName: hisco
    Password: hisco
# Naver Cloud Config
ncp:
  account:
    accessKey: aa
    secretKey: vv
    apiKey: bb

# JWT Default Expiration Config
# Access Expires Hour, Refresh Expires Day
jwt:
  defaultAccessExpires: 1
  defaultRefreshExpires: 30
  secretKey: customKeyTag
