# 클라우드 운영 서버(Prod) development environment Profiles Setting
spring:
  config:
    activate:
      on-profile: local


# Logback Config
logging:
  file:
    path: c:/tmp/newFmcs/local
  level:
    root: warn
    default_level: info
    pretty: debug
    org.zalando.logbook: off
    schedule_level: debug
    com.custom: debug
    jdbc:
      default: ERROR
      sqlonly: OFF
      sqltiming: INFO
      audit: ERROR
      resultset: ERROR
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 1GB

# MariaDB Config
Globals:
  DbType: maria
  maria:
#    DriverClassName: org.mariadb.jdbc.Driver
    DriverClassName: net.sf.log4jdbc.DriverSpy
#    Url: jdbc:mariadb://localhost:3306/custom
    Url: jdbc:log4jdbc:mariadb://localhost:3306/custom?allowPublicKeyRetrieval=true&useSSL=false
    UserName: root
    Password: 220617
# Naver Cloud Config
ncp:
  account:
    accessKey: aa
    secretKey: vv
    apiKey: bb

# JWT Default Expiration Config
# Access Expires Hour, Refresh Expires Day
jwt:
  defaultAccessExpires: 1
  defaultRefreshExpires: 30
  secretKey: customKeyTag
