# 클라우드 운영 서버(Prod) development environment Profiles Setting
spring:
  config:
    activate:
      on-profile: prod

# Logging Config
logging:
  file:
    path: c:/tmp//prod
  level:
    root: off
    default_level: warn
  logback:
    rollingpolicy:
      max-history: 60
      max-file-size: 5GB

# MariaDB Config
Globals:
  DbType: maria
  maria:
#    DriverClassName: org.mariadb.jdbc.Driver
    DriverClassName: net.sf.log4jdbc.DriverSpy
#    Url: jdbc:mariadb://localhost:3306/custom
    Url: jdbc:log4jdbc:mariadb://localhost:3306/custom
    UserName: custom
    Password: 220617
