# Default Profiles Setting

# Spring Boot Config
spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
# Server Config
server:
  port: 8090
  servlet: 
    context-path: /

# Logback Config
logging:
  file:
    name: restapi
    schedule_name: restScheduling
  level:
    root: off
    com.custom: debug
    jdbc:
      default: ERROR
      sqlonly: INFO
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 1GB

# MariaDB Config
Globals:
  DbType: maria
  maria:
    DriverClassName: net.sf.log4jdbc.DriverSpy
    Url: jdbc:log4jdbc:mariadb://localhost:3306/custom?allowPublicKeyRetrieval=true&useSSL=false
    UserName: root
    Password: 220617
  page:
    pageUnit: 10
    pageSize: 10
    paging: false
